ARG SWIFT_IMAGE
FROM ${SWIFT_IMAGE}

ARG SDK_URL
ARG CHECKSUM

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update -y && apt-get install -y curl file

RUN swift sdk install ${SDK_URL} --checksum ${CHECKSUM}
