ARG SWIFT_IMAGE
FROM ${SWIFT_IMAGE}

ARG SWIFT_VERSION
ARG SDK_SNAPSHOT
ARG CHECKSUM

ENV TAG=${SWIFT_VERSION}-RELEASE

RUN swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-${TAG}/swift-wasm-${TAG}-wasm32-unknown-wasi.artifactbundle.zip --checksum $CHECKSUM
