ARG SWIFT_VERSION
FROM swift:${SWIFT_VERSION}-jammy

RUN apt-get update && apt-get install -y \
    libssl-dev \
    sqlite3 libsqlite3-dev   `# SPI-Server` \
    libcurl4-openssl-dev     `# SPI-Server` \
    libgtk-3-dev clang       `# swift-cross-ui` \
    libjemalloc-dev          `# ordo-one/package-benchmark`

RUN git config --global init.defaultBranch main
