# swiftlang/swift:nightly-jammy
# Tag: swift-DEVELOPMENT-SNAPSHOT-2024-02-08-a
FROM swiftlang/swift@sha256:bc03949471dfe27b7b22e78e0c3a622b014d9e002806883b5f0a8d6874c53754

ARG SWIFT_VERSION
# See https://github.com/swiftwasm/swift/releases
ENV TAG=$SWIFT_VERSION-SNAPSHOT-2024-02-08-a
# options: aarch64 x86_64
ARG ARCH=x86_64
# jammy = ubuntu 22.04
ARG PLATFORM=ubuntu22.04

RUN swift experimental-sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-${TAG}/swift-wasm-${TAG}-${PLATFORM}_${ARCH}.artifactbundle.zip
